version: '3'
services:
  redis-server:
    image: 'redis'
  postgres-server:
    image: 'postgres:11'
    environment:
      - POSTGRES_DB=cheststore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cheststore
  cheststore:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:cheststore@postgres-server:5432/cheststore
      - PORT=8000
      - REDIS_URL=redis://redis-server:6379
